export function deduplicateSlug(slug) {
  if (!slug || typeof slug !== 'string') return '';
  let trimmed = slug.trim().toLowerCase();
  while (trimmed.length >= 4 && trimmed.length % 2 === 0) {
    const half = trimmed.slice(0, trimmed.length / 2);
    if (half === trimmed.slice(trimmed.length / 2) && /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(half)) {
      trimmed = half;
    } else {
      break;
    }
  }
  return trimmed;
}

export function resolvePublicRoute(pathname, fallbackEventSlug, hash = '', search = '') {
  const queryRoute = new URLSearchParams(search).get('route');
  const rawRouteSource = queryRoute?.startsWith('/') ? queryRoute : hash.startsWith('#/') ? hash.slice(1) : pathname;
  // Be tolerant of links generated by older builds where `?preview=1` was
  // accidentally embedded in the route parameter itself.
  const routeSource = rawRouteSource.split(/[?#]/, 1)[0];
  const segments = routeSource.split('/').filter(Boolean).map(decodeURIComponent);
  const organizerIndex = segments.indexOf('organizer');
  if (organizerIndex >= 0) {
    const organizerPage = segments[organizerIndex + 1] || 'dashboard';
    return {kind: 'organizer', page: organizerPage};
  }
  const accountIndex = segments.findIndex((seg) => seg === 'account' || seg === 'login' || seg === 'register');
  if (accountIndex >= 0) {
    const seg = segments[accountIndex];
    const page = seg === 'register' ? 'register' : seg === 'login' ? 'login' : (segments[accountIndex + 1] || 'overview');
    return {kind: 'account', page};
  }
  const eventIndex = segments.indexOf('events');
  if (eventIndex < 0) return {kind: 'catalog'};
  const rawEventSlug = segments[eventIndex + 1];
  if (!rawEventSlug) return {kind: 'catalog'};
  const eventSlug = deduplicateSlug(rawEventSlug);
  const showSlug = segments[eventIndex + 2] === 'shows' ? segments[eventIndex + 3] : undefined;
  return {kind: 'detail', eventSlug, ...(showSlug ? {showSlug} : {})};
}

export function buildPublicPath(pathname, target) {
  const segments = pathname.split('/').filter(Boolean);
  const eventIndex = segments.indexOf('events');
  const baseSegments = eventIndex >= 0
    ? segments.slice(0, eventIndex)
    : pathname.endsWith('/') ? segments : segments.slice(0, -1);
  const base = `/${baseSegments.join('/')}${baseSegments.length ? '/' : ''}`;
  const [pathOnly, queryOrHash] = target.replace(/^\/+/, '').split(/([?#].*)/, 2);
  const cleanTarget = pathOnly.split('/').map((seg, idx, arr) => {
    if (
      arr[idx - 1] === 'events' ||
      (idx === 0 && seg !== 'events' && seg !== 'organizer' && seg !== 'account' && seg !== 'login' && seg !== 'register')
    ) {
      return deduplicateSlug(seg);
    }
    return seg;
  }).join('/');
  const suffix = queryOrHash?.startsWith('?')
    ? `&${queryOrHash.slice(1)}`
    : queryOrHash || '';
  return `${base}?route=/${cleanTarget}${suffix}`;
}

export function navigatePublicRoute(target) {
  if (typeof window === 'undefined') return;
  const nextUrl = buildPublicPath(window.location.pathname, target);
  window.history.pushState({}, '', nextUrl);
  window.dispatchEvent(new PopStateEvent('popstate'));
}
